[package]
name = "cliparse"
version = "2.0.0"
edition = "2021"
author = "Lovis Rentsch"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
